name: atlas
favicon: null
layout_spectrum: 0.04504873417317867
typography_spectrum: 0.2120486036874354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.54882229026407
  lightness: 0.5166177456267178
  saturation: 0.292203278047964
  rhythmicContrast: 0.3419997380115092
purpose: []
