name: atlas
favicon: null
layout_spectrum: 0.32922
typography_spectrum: 0.23011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0e0d'
    - '#ffffff'
    - '#91c1ff'
    - '#3d69d4'
    - '#870c1e'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
